print("Give me your 1st result")
average = int(input())
print("Give me your 2nd result")
average = average + int(input())
print("Give me your 3rd result")
average = average + int(input())
print("Give me your 4th result")
average = average + int(input())
print("Give me your 5th result")
average = average + int(input())
print("The average of your results is " + str(average))