print("Give me your 1st number")
value1 = int(input())
print("Give me your 2nd number")
value2 = int(input())
print("Give me your 3rd number")
value3 = int(input())
value = min(value1, value2, value3)
Value = max(value1, value2, value3)
print("The smallest value is " + str(value))
print("The biggest value is " + str(Value))